version: "3.7"
services:
  db57:
    image: mysql:5.7
    # restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"

  app:
    # image: node:14-alpine
    user: $DOCKER_USER
    image: node:18-alpine3.14
    working_dir: /app
    # restart: always
    env_file:
      - .env
    environment: 
      - MYSQL_HOST=db57
    command: sh -c "npm i && npm run dev"
    ports:
      - "3333:3333"
      - "8080:8080"
    volumes:
      - "./:/app"

    depends_on: 
      - db57
